# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birthdate',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 19, 26, 16, 97107)),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(0, 14400), '4:00'), (datetime.timedelta(0, 10800), '3:00'), (datetime.timedelta(0, 12600), '3:30'), (datetime.timedelta(0, 16200), '4:30'), (datetime.timedelta(0, 5400), '1:30'), (datetime.timedelta(0, 3600), '1:00'), (datetime.timedelta(0, 7200), '2:00'), (datetime.timedelta(0, 9000), '2:30')], default=datetime.timedelta(0, 3600)),
        ),
    ]
