# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0003_auto_20160617_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 17, 14, 33, 12, 662629)),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(0, 9000), '2:30'), (datetime.timedelta(0, 5400), '1:30'), (datetime.timedelta(0, 16200), '4:30'), (datetime.timedelta(0, 3600), '1:00'), (datetime.timedelta(0, 10800), '3:00'), (datetime.timedelta(0, 7200), '2:00'), (datetime.timedelta(0, 12600), '3:30'), (datetime.timedelta(0, 14400), '4:00')], default=datetime.timedelta(0, 3600)),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 17, 14, 33, 12, 686650, tzinfo=utc)),
        ),
    ]
